# -*- coding: utf-8 -*-
"""
Inventory and Sales Analysis Project
Author: Deniz Çağla Otağ
"""



"""inventory-analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oYryNJDWlYrT_OB5JwCCnmCCjWUa9nWJ
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_excel("inventory.xlsx")
print("Inventory data loaded successfully.\n")


name_col = data.columns[1]
category_col = data.columns[2]
price_col = data.columns[3]
stock_col = data.columns[4]
sold_col = data.columns[5]


revenue_list = []

for i in range(len(data)):
    price = data.loc[i, price_col]
    sold = data.loc[i, sold_col]
    revenue = price * sold
    revenue_list.append(revenue)

data["Revenue"] = revenue_list



total_revenue = 0
for r in data["Revenue"]:
    total_revenue += r



max_sold = data[sold_col].max()

for i in range(len(data)):
    if data.loc[i, sold_col] == max_sold:
        best_product_name = data.loc[i, name_col]
        best_product_category = data.loc[i, category_col]
        best_product_revenue = data.loc[i, "Revenue"]



low_stock_list = []

for i in range(len(data)):
    if data.loc[i, stock_col] < 10:
        low_stock_list.append(data.loc[i])

low_stock_df = pd.DataFrame(low_stock_list)



category_revenue = {}

for category in data[category_col].unique():
    total = 0
    for i in range(len(data)):
        if data.loc[i, category_col] == category:
            total += data.loc[i, "Revenue"]
    category_revenue[category] = total



print("=== INVENTORY DATA ===")
print(data)

print("\nTotal Revenue:", total_revenue)

print("\n=== BEST SELLING PRODUCT ===")
print("Product:", best_product_name)
print("Category:", best_product_category)
print("Revenue:", best_product_revenue)

print("\n=== LOW STOCK PRODUCTS ===")
print(low_stock_df)

print("\n=== CATEGORY BASED REVENUE ===")
for c in category_revenue:
    print(c, ":", category_revenue[c])



plt.figure()
plt.bar(category_revenue.keys(), category_revenue.values())
plt.xlabel("Category")
plt.ylabel("Revenue")
plt.title("Revenue by Category")
plt.show()



data.to_excel("inventory_report.xlsx", index=False)
